# Generated by Django 4.0.4 on 2022-05-02 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AccountUsers', '0003_remove_AccountUser_brand_name_remove_AccountUser_email'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products',
                                               to='products.category')),
                ('AccountUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products',
                                             to='AccountUsers.AccountUser')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
