# Generated by Django 4.0.4 on 2022-08-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountuser',
            old_name='type',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='accountuser',
            old_name='created_by',
            new_name='user',
        ),
    ]
