# Generated by Django 4.0.4 on 2022-05-02 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('AccountUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='AccountUser',
            options={'ordering': ['username', 'date_time_created']},
        ),
        migrations.RenameField(
            model_name='AccountUser',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='AccountUser',
            name='last_name',
        ),
    ]
