# Generated by Django 4.0.4 on 2022-05-02 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('AccountUsers', '0002_alter_AccountUser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='AccountUser',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='AccountUser',
            name='email',
        ),
    ]
