# Generated by Django 4.0.4 on 2022-07-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountUsers', '0006_AccountUser_email_AccountUser_first_name_AccountUser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='AccountUser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='AccountUser',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
