# Generated by Django 4.0.4 on 2022-08-14 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='delivery_frequency',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='service_delivery', to='store.deliveryperiod'),
        ),
        migrations.AddField(
            model_name='services',
            name='policy',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='services_policy', to='store.policy'),
        ),
    ]
