# Generated by Django 4.0.4 on 2022-08-12 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='in_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='in_stock',
            new_name='is_stock',
        ),
        migrations.AlterField(
            model_name='products',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_policy', to='products.productpolicy'),
        ),
    ]
