# Generated by Django 4.0.4 on 2022-09-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_review_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['slug']},
        ),
        migrations.RemoveField(
            model_name='policy',
            name='payment_terms',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.services'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='service_terms',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
