# Generated by Django 4.0.4 on 2022-09-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_brand_options_remove_policy_payment_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='store.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='delivery_frequency',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='delivery_frequency', to='store.deliveryperiod'),
        ),
        migrations.AlterField(
            model_name='products',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_policy', to='store.policy'),
        ),
        migrations.AlterField(
            model_name='services',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_policy', to='store.policy'),
        ),
    ]
