# Generated by Django 4.0.4 on 2022-08-14 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0003_alter_services_delivery_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='policy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_policy', to='store.policy'),
        ),
        migrations.AlterField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='accounts.customuser'),
        ),
    ]
