# Generated by Django 4.0.4 on 2022-08-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0004_alter_products_policy_alter_products_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='delivery_frequency',
        ),
        migrations.AlterField(
            model_name='products',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_policy', to='store.policy'),
        ),
        migrations.AlterField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='accounts.customuser'),
        ),
        migrations.AlterField(
            model_name='services',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services_policy', to='store.policy'),
        ),
    ]
