# Generated by Django 4.0.4 on 2022-05-03 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('vendors', '0003_remove_vendor_brand_name_remove_vendor_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name', 'date_time_created']},
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='username',
            new_name='name',
        ),
    ]
