# Generated by Django 4.0.4 on 2022-05-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vendors', '0004_alter_vendor_options_rename_username_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='intro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
