# Generated by Django 4.0.4 on 2022-05-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
