# Generated by Django 4.0.4 on 2022-05-04 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
    ]
